package dev.rezastallone.cartrackchallange.constant

const val SHARED_PREFERENCE_NAME = "CARTRACK_SHARED_PREFERENCE_NAME"
const val PREF_SIGNEDIN_USERNAME = "PREF_SIGNEDIN_USERNAME"
const val VALID_LOCAL_OFFSET = "VALID_LOCAL_OFFSET"